---
# tasks file for maven-role
- name: Download and unarchive package
  unarchive:
    src: https://miroir.univ-lorraine.fr/apache/maven/maven-3/{{maven_version}}/binaries/apache-maven-{{maven_version}}-bin.tar.gz
    dest: "{{maven_home_parent_directory}}"
    copy: no

- name: Add maven as executable to PATH
  file:
    src: "{{maven_home_parent_directory}}/apache-maven-{{maven_version}}/bin/mvn"
    dest: /usr/bin/mvn
    state: link

- name: Configuration de maven
  lineinfile: 
    dest: "{{maven_env_file}}"
    line: "{{item}}"
    create: yes
    state: present
  loop:
  - "M2_HOME={{maven_home_parent_directory}}/apache-maven-{{maven_version}}"
  - "PATH=$PATH:$M2_HOME/bin"

- name: Run maven configuration file
  shell: ". {{maven_env_file}}" 
